
GET http://localhost:3000/agenda/?date=2020-9-22
Content-Type: application/json

###

GET http://localhost:3000/todos/

###

POST http://localhost:3000/todos/ 
Content-Type: application/json

{
 "id": 7,
 "todo": "Finalize event theme",
 "priority": "LOW",
 "status": "TO DO",
 "category": "HOME",
 "dueDate": "2021-02-22"
}
###

DELETE http://localhost:3000/todos/6/
Content-Type: application/json

###

PUT http://localhost:3000/todos/3/
Content-Type: application/json 

{ "category": "LEARNING" }